services:
  - type: web
    name: vn-index-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true

  - type: cron
    name: daily-vnindex-scraper
    env: python
    schedule: "0 11 * * 1-5"  # 6PM VN time
    buildCommand: pip install -r requirements.txt
    startCommand: bash run_scrape.sh